### ISSUE TITLE
Error on migrating reference data. BundleConfigFetcher::fetch() must be of type array.

### ISSUE THREAD

**Issue by manuelgomez-urbanara** [akeneo/transporteo#141]
I get an error on the reference data migration step:

Destination PIM database initialization...
Migrating files data...
Migrating structure data...
Migrating families data...
Migrating system data...
Migrating jobs data...
Migrating groups data...
Migrating extra data...
Migrating enterprise edition data...
Migrating reference data...
PHP Fatal error:  Uncaught TypeError: Return value of Akeneo\PimMigration\Domain\DataMigration\BundleConfigFetcher::fetch() must be of the type array, null returned in /var/docker/transporteo/transporteo/src/Domain/DataMigration/BundleConfigFetcher.php:36
Stack trace:
#0 /var/docker/transporteo/transporteo/src/Domain/MigrationStep/s130_ReferenceDataMigration/ReferenceDataMigrator.php(69): Akeneo\PimMigration\Domain\DataMigration\BundleConfigFetcher->fetch(Object(Akeneo\PimMigration\Domain\Pim\SourcePim), 'PimReferenceDat...')
#1 /var/docker/transporteo/transporteo/src/Infrastructure/MigrationStep/S130FromDestinationPimEnterpriseEditionDataMigratedToDestinationPimReferenceDataMigrated.php(52): Akeneo\PimMigration\Domain\MigrationStep\s130_ReferenceDataMigration\ReferenceDataMigrator->migrate(Object(Akeneo\PimMigration\Domain\Pim\SourcePim), Object(Akeneo\PimMigration\Domain\Pim\DestinationPim))
#2 [internal function]: Akeneo\PimMigration\Infrastructure\MigrationStep\S130FromDestinationPimEnterpriseEditionDataMigratedToDestinati in /var/docker/transporteo/transporteo/src/Domain/DataMigration/BundleConfigFetcher.php on line 36

Anybody knows about this??

Thanks!

Source: Version (EE): 1.7.20 Artichoke  Version (CE): 1.7.20 The Old Grey Hare  
Destination: Version (EE): 2.0.26 Hazel  Version (CE): 2.0.26 Rebel Rabbit

**Comment by buttash** [comment]
I'm getting the same issue:

Destination PIM database initialization...
Migrating files data...
Migrating structure data...
Migrating families data...
Migrating system data...
Migrating jobs data...
Migrating groups data...
Migrating extra data...
Migrating reference data...
# Current configuration for "PimReferenceDataBundle"
PHP Fatal error:  Uncaught TypeError: Return value of Akeneo\PimMigration\Domain\DataMigration\BundleConfigFetcher::fetch() must be of the type array, null returned in /var/www/transporteo/src/Domain/DataMigration/BundleConfigFetcher.php:36
Stack trace:
#0 /var/www/transporteo/src/Domain/MigrationStep/s130_ReferenceDataMigration/ReferenceDataMigrator.php(69): Akeneo\PimMigration\Domain\DataMigration\BundleConfigFetcher->fetch(Object(Akeneo\PimMigration\Domain\Pim\SourcePim), 'PimReferenceDat...')
#1 /var/www/transporteo/src/Infrastructure/MigrationStep/S130FromDestinationPimEnterpriseEditionDataMigratedToDestinationPimReferenceDataMigrated.php(52): Akeneo\PimMigration\Domain\MigrationStep\s130_ReferenceDataMigration\ReferenceDataMigrator->migrate(Object(Akeneo\PimMigration\Domain\Pim\SourcePim), Object(Akeneo\PimMigration\Domain\Pim\DestinationPim))
#2 [internal function]: Akeneo\PimMigration\Infrastructure\MigrationStep\S130FromDestinationPimEnterpriseEditionDataMigratedToDestinationPimReferenceDataMigrated->onDestinationPimR in /var/www/transporteo/src/Domain/DataMigration/BundleConfigFetcher.php on line 36

I'm migrating from 1.7.2 to 2.0.x

Any thoughts on what might be causing this?
Thanks
Martin

**Comment by ttraskback** [comment]
Hi,
Stumbled upon this to and solved it by giving app/console executable rights on the source.
