### ISSUE TITLE
Error during "Migrating Products Data"

### ISSUE THREAD

**Issue by adamrandazzo** [akeneo/transporteo#95]
I have received an error during the "Migrating Products Data..." portion of the process.

```
Migrating files data...
Migrating structure data...
Migrating families data...
Migrating system data...
Migrating jobs data...
Migrating groups data...
Migrating extra data...
Migrating reference data...
Migrating products data...
PHP Fatal error:  Uncaught Error: Call to a member function execute() on null in /root/transporteo/src/Infrastructure/Cli/SshConsole.php:51
Stack trace:
#0 /root/transporteo/src/Domain/Command/ChainedConsole.php(23): Akeneo\PimMigration\Infrastructure\Cli\SshConsole->execute(Object(Akeneo\PimMigration\Domain\Command\Api\ListAllProductsCommand), Object(Akeneo\PimMigration\Domain\Pim\SourcePim))
#1 /root/transporteo/src/Domain/MigrationStep/s140_ProductMigration/ProductMigrator.php(64): Akeneo\PimMigration\Domain\Command\ChainedConsole->execute(Object(Akeneo\PimMigration\Domain\Command\Api\ListAllProductsCommand), Object(Akeneo\PimMigration\Domain\Pim\SourcePim))
#2 /root/transporteo/src/Domain/MigrationStep/s140_ProductMigration/ProductMigrator.php(56): Akeneo\PimMigration\Domain\MigrationStep\s140_ProductMigration\ProductMigrator->migrateProducts(Object(Akeneo\PimMigration\Domain\Pim\SourcePim), Object(Akeneo\PimMigration\Domain\Pim\DestinationPim))
#3 /root/transporteo/src/Infrastructure/MigrationStep/S140FromDestinationPimRe in /root/transporteo/src/Infrastructure/Cli/SshConsole.php on line 51
```
This is coming from a remote installation of 1.7.5 into a 2.0.1 version of Akeneo. In checking the database, it appears that no products were migrated at all. All other data seems to have worked correctly.

**Comment by LaurentPetard** [comment]
Hello @adamrandazzo ,

Thanks for reporting this issue. There's indeed a service injection that is missing in SshConsole.php 

We'll fix this as soon as possible.

**Comment by momoss** [comment]
Hello @adamrandazzo,

The issue has been fixed and will be in the next patch released very soon, so I close the issue.

Best regards.
